/**
 * All action constants for autoAcro
 * Action type format: [Namespace].[ActionType].[ActionTarget]
 */
const AUTOACRO = {
	ADD: {
		ACRO: 'AUTOACRO.ADD.ACRO',
		DUP: 'AUTOACRO.ADD.DUP',
	},
	CANCEL: 'AUTOACRO.CANCEL',
	CLEAR: 'AUTOACRO.CLEAR',
	END: 'AUTOACRO.END',
	ERROR: 'AUTOACRO.ERROR',
	MERGE: {
		ACROS: 'AUTOACRO.MERGE.ACROS',
		ACROMAP: 'AUTOACRO.MERGE.ACROMAP',
	},
	SET: {
		ACROS: 'AUTOACRO.SET.ACROS',
		ACROMAP: 'AUTOACRO.SET.ACROMAP',
		DUPS: 'AUTOACRO.SET.DUPS',
		DUPSMAP: 'AUTOACRO.SET.DUPSMAP',
		DUPS_SELECTIONS: 'AUTOACRO.SET.DUPS_SELECTIONS',
		NODEFS: 'AUTOACRO.SET.NODEFS',
		NODEFSMAP: 'AUTOACRO.SET.NODEFSMAP',
	},
	START: 'AUTOACRO.START',
	SUBMIT: {
		ACROLIST: 'AUTOACRO.SUBMIT.ACROLIST',
		CHOOSEDUPS: 'AUTOACRO.SUBMIT.CHOOSEDUPS',
		NODEFS: 'AUTOACRO.SUBMIT.NODEFS',
	},
	REMOVE: {
		ACRO: 'AUTOACRO.REMOVE.ACRO',
	},
};

export default AUTOACRO;